// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbRQ6uzjMi_7OpcJI6f0ZJEvBd8xT7IsY',
    appId: '1:939544369119:web:4c614d815a576122ba166a',
    messagingSenderId: '939544369119',
    projectId: 'eliteform-9f2fc',
    authDomain: 'eliteform-9f2fc.firebaseapp.com',
    storageBucket: 'eliteform-9f2fc.firebasestorage.app',
    measurementId: 'G-PV4P008WB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4gZ8Y7QCemSJHvyRubS0BFtKWI8HOZhA',
    appId: '1:939544369119:android:12ca6edee9257e84ba166a',
    messagingSenderId: '939544369119',
    projectId: 'eliteform-9f2fc',
    storageBucket: 'eliteform-9f2fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKvG8A61w-lNq1qJFcCnm3QQPTWuEp9uc',
    appId: '1:939544369119:ios:aec1d68a173efec5ba166a',
    messagingSenderId: '939544369119',
    projectId: 'eliteform-9f2fc',
    storageBucket: 'eliteform-9f2fc.firebasestorage.app',
    iosClientId: '939544369119-igo0ocpal0gd4aidfg6v0g667g9s73q0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eliteform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKvG8A61w-lNq1qJFcCnm3QQPTWuEp9uc',
    appId: '1:939544369119:ios:aec1d68a173efec5ba166a',
    messagingSenderId: '939544369119',
    projectId: 'eliteform-9f2fc',
    storageBucket: 'eliteform-9f2fc.firebasestorage.app',
    iosClientId: '939544369119-igo0ocpal0gd4aidfg6v0g667g9s73q0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eliteform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbRQ6uzjMi_7OpcJI6f0ZJEvBd8xT7IsY',
    appId: '1:939544369119:web:f70ca6ab1734f229ba166a',
    messagingSenderId: '939544369119',
    projectId: 'eliteform-9f2fc',
    authDomain: 'eliteform-9f2fc.firebaseapp.com',
    storageBucket: 'eliteform-9f2fc.firebasestorage.app',
    measurementId: 'G-XN7E1GMDHQ',
  );
}
